### ISSUE TITLE
Install wirequery on Openshift 

### ISSUE THREAD

**Issue by Meza1923** [wirequery/wirequery#17]
Hey, 

I’m trying to deploy wirequery on Openshift in on perm, I have deployed Redis and crunchy for this, and I running into some issues
Could you please help me to understand what am I do wrong?
The error now is 
‘’’
Error creating bean with name “flywayinitializer” define in class path resource…. Unable to obtain connection from database: the connection attempt failed
‘’’

thank you in advance

**Comment by wnederhof** [comment]
Hey! Really cool that you're giving WireQuery a try!

I think something may have gone wrong with the environment variables of the app. Check out: https://github.com/wirequery/wirequery/blob/main/docker-compose.yml for an example. In this specific case, have a look at the following parameters:
- SPRING_FLYWAY_USER
- SPRING_FLYWAY_PASSWORD
- SPRING_FLYWAY_URL
Let me know how it goes!

**Comment by Meza1923** [comment]
hey, 

It's seems like a great tool, exactly what we looking for..
Sorry for the delay, I was out of office...
thank you for your response, I think that this values aren't in the helm chart value file, it might be?
the only values I saw is:

```
wirequery-backend:
  settings:
    dbMigrateUser: <crunchy-admin> let say **test**
    dbMigratePassword: <crunchy-admin-password> **123456**
    dbMigrateJdbcUrl: "jdbc:postgresql://crunchy-svc:5432/wirequery"
    redisHostName: redis-svc
    redisPort: "6379"
    dbUser: wirequery-multitenant
    dbPassword: wirequery-multitenant
    dbUrl: "jdbc:postgresql://wirequery-postgresql:5432/wirequery"
    adminEnabled: "true"
    tenantId: "0"
    disableMultitenancy: true
    adminPassword: admin
```
Could you please help me find out what should I set in order to let it work?

Thanks a lot in advanced
